### ISSUE TITLE
Redirect new users to Join Party

### ISSUE THREAD

**Issue by nreid26** [partyshark/partyShark#36]
When a new user attempts to enter a party they are unregistered in they should be redirected to the party join page with the party code filled in via the supplied url

**Comment by rileyBloomfield** [comment]
I  think less interaction by the user would be best. Currently on a refresh or link click, they are taken right to that party from the url and joined automatically. This can be changed, thoughts?

**Comment by nreid26** [comment]
I see it as an expectation issue.  Signing people in immediately doesn't tell them what's going on (as clearly) and maybe they don't really want to join.  We should give them the option not too.
