### ISSUE TITLE
Add album art to now playing

### ISSUE THREAD

**Issue by cdoyle45** [partyshark/partyShark#37]
I don't know the angular syntax for this

**Comment by cdoyle45** [comment]
Deezer current_track subscription only returns the following (ie. no album art)

{
index: 0,
track: {
    album: {...},
    artist: {...},
    duration: 123,
    id: 2322,
    title: "track title",
}
}

**Comment by rileyBloomfield** [comment]
Art is stored in the play through objects playthrough.song.art . When a song is added, {{trackArt}} can be set to the play through art and {{trackArt}} should be set to empty when finished. Angular directive is <src ng-src='{{trackArt}}' alt=''/> and variable is accessed in controller by $scope.trackArt
