### ISSUE TITLE
iOS app colours wrong / not consistant with webapp

### ISSUE THREAD

**Issue by cdoyle45** [partyshark/partyShark#38]

**Comment by rileyBloomfield** [comment]
If it looks good we can change web app to match

**Comment by RiZhao** [comment]
The orange?

**Comment by cdoyle45** [comment]
I meant the blue text on orange in the menu bar. Very minor fix.
Orange we are using is #FA6900

**Comment by RiZhao** [comment]
will change blue to match website blue
