### ISSUE TITLE
Website doesn't provide party code to join party with

### ISSUE THREAD

**Issue by RiZhao** [partyshark/partyShark#41]

**Comment by rileyBloomfield** [comment]
party code is in link, should it be on the options page along with the admin code too do you think?

**Comment by nreid26** [comment]
Maybe put "Or send a link" next to it.  The URL is visible in the address bar and people are used to sending links.

**Comment by nreid26** [comment]
Plus mobile site users will already have that functionality baked into their browser

**Comment by ryanToth** [comment]
Definitely put it in the options page
